[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib/',
    '@layerzerolabs/test-devtools-evm-foundry/=lib/devtools/packages/test-devtools-evm-foundry/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'solidity-bytes-utils/contracts/=lib/solidity-bytes-utils/contracts/',
    '@layerzerolabs/lz-evm-v1-0.7/contracts/=lib/layerzero-v1/contracts/',
    '@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/',
    '@uniswap/v3-core/contracts/=lib/v3-core/contracts/'
]

# File system permissions for reading deployment files
fs_permissions = [
    { access = "read", path = "./script"},
    { access = "read", path = "./layerzero-deployments.json"},
    { access = "read", path = "./layerzero-dvns.json"},
    { access = "read", path = "./utils/wire-config.json"},
    { access = "read-write", path = "./deployments"}
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
